### PR TITLE
feat(metrics): fix codeclimate configuration

### PR DESCRIPTION
**Pull request by dblandin**
### Description

Remove unanalyzed file extensions from CC exclude_paths

`*` at the beginning of a value produces invalid YAML. Normally the fix would
be to wrap these values in quotes, but in this case I think it makes more sense
to remove the lines as these file extensions aren't analyzed by any enabled
engine.

Add `npm-shrinkwrap.json` file for CC nodesecurity engine

Since the Code Climate nodesecurity engine runs its underlying tool in
`offline` mode, a `npm-shrinkwrap.json` file must be present during analysis.
#### Added
- _List added features here_
#### Removed
- _List removed features here_
#### Fixed
- _List fixed bugs here_
#### Changed
- Updated `.codeclimate.yml` configuration file to fix Code Climate builds
- Generated and committed `npm-shinkwrap.jspn` file for Code Climate nodesecurity engine
- Add `node_modules` folder to Code Climate exclude_paths
#### Deprecated
- _List any feature that is being deprecated in this_
### Existing PRs with overlapping scope
- #318 - feat(metrics): configuration for codeclimate
### Screenshots of changes

_(if modifying a view)_
### Checklist
- [x] This PR passes Linting tests (see below)
- [x] This PR does not contain merge conflicts with `develop` (see below)
- [x] This PR does not contain:
  - Additional Dependencies in `package.json` that are not used
  - Frontend JS in Jade templates (unless absolutely necessary)

### CODE REVIEW

**Comment by johngluck65** [comment]
Hey @dblandin sorry  I broke this.  I fixed it up and it is now in the mainline, however I did want to disable images.  I disabled the node-security engine because I didn't want to muck with shrinkwrap However, if you think you got it to work, we should keep that and I'll re-enable node-security

**Comment by johngluck65** [comment]
I propose we close this PR without merging since it contains more than shrinkwrap and those changes will revert some of my changes, specifically the image scan and disabling of node-security.  Once we figure out how to get shrinkwrap configured, we can re-endable node-security.  Yes?

**Comment by johngluck65** [comment]
Yeah, that would be great.  Just to be clear, the ideal end state is that images are not scanned and node-security is enabled.

**Comment by dblandin** [comment]
Hey @therebelrobot @johngluck65!

> I fixed it up and it is now in the mainline, however I did want to disable images.

Did you encounter an issue without explicitly excluding images? I'm not aware of any Code Climate engines that scan images for issues, so I don't think the explicits exclude are necessary, but they certainly don't hurt.

Since Code Climate runs the node security project CLI in offline mode, a `npm-shrinkwrap-json` file must be present in the repo. I was able to generate this one pretty easily by running a fresh `npm install` and then `npm shrinkwrap`.

I ran a Code Climate analysis locally using the CLI without any errors. I'd also recommend enabling Code Climate PR integration so you can see, before merging, whether these changes have the desired effect. You can find that option within your Code Climate repo settings, under integrations.

Happy to back out the `exclude_paths` update if you'd like to keep those explicit ignores in place. Also not sure what's up with the Travis build.

**Comment by dblandin** [comment]
Well it looks like running `npm install --no-shrinkwrap` on Travis fixed the build.

Here's the relevant GH issue: https://github.com/npm/npm/issues/3436

**Comment by johngluck65** [comment]
Okay, I accept that explanation.  Thanks for fixing this up for us @dblandin 

@therebelrobot, I'll close my other PR.  We still need to disable eslint.  I can add that change to this PR or submit a new PR once this one is merged.

**Comment by dblandin** [comment]
Thanks for the merge!

@johngluck65 What's the reason for disabling ESLint? Looks like the ESLint engine ran successfully in [this recent build](https://codeclimate.com/github/sfbrigade/brigadehub/builds/13) and I can see see the [issues emitted](https://codeclimate.com/github/sfbrigade/brigadehub/issues?engine=eslint). If you're interested, we just [released support for ESLint 2](https://codeclimate.com/changelog/574dc95efdd7dc0090002225). The engine still defaults to ESLint 1.

Let me know if I can help!

**Comment by johngluck65** [comment]
@dblandin We are already running feross/standard in the pre-commit hook, so there is no need to adhere to two standards and there is not yet a codeclimate engine for standard.

**Comment by dblandin** [comment]
@johngluck65 That's true, we don't yet have an engine specifically for Standard Style but our ESLint engine supports @feross's Standard Style via vendored npm packages ([xjamundx/eslint-plugin-standard](https://github.com/xjamundx/eslint-plugin-standard) and [feross/eslint-config-standard](https://github.com/feross/eslint-config-standard)) [as of this week](https://github.com/codeclimate/codeclimate-eslint/pull/95)!

**Comment by johngluck65** [comment]
@dblandin I like to see that mature before enabling it in our pipeline, but I think that's a step in the right direction.

**Comment by dblandin** [comment]
@johngluck65 Sounds good! You might consider enabling Code Climate PR integration but keeping it disabled as a required status check until you're sure it's a good fit. Thanks for the feedback!

**Comment by johngluck65** [comment]
@dblandin It's not clear to me how to do that.   And if we did that, would eslint issues still count against our GPA?  If so, we wouldn't want to do that.

**Comment by dblandin** [comment]
> It's not clear to me how to do that.

We have documentation on how to set up GitHub integration (including PRs) for Code Climate  [here](https://docs.codeclimate.com/docs/github#pull-requests).

The gist is to:
- Point a GitHub webhook for this repo to Code Climate so we know when commits are pushed and PRs are opened.
- Configure a personal access token from GitHub so Code Climate can update its status line on PRs.

> And if we did that, would eslint issues still count against our GPA? If so, we wouldn't want to do that.

That's a great question. Ratings are calculated for any file included within your ratings paths ([details](https://docs.codeclimate.com/docs/ratings)), and are included within your GPA. We don't currently have a way to exclude a particular engine's issues from your ratings, so disabling it would be the only way to prevent it from affecting your GPA. You can always run the engine locally with the [CLI](https://github.com/codeclimate/codeclimate) to view the issues it would report.

A nice feature of our GitHub PR integration is that for any PR you can see the potential change in GPA. So one approach might be to disable ESLint in your default branch (`develop` in your case), open up a PR enabling the engine, and iterate on the ESLint config and/or fix the issues reported until you're happy with the GPA change.

I didn't notice this before but it looks like you may want to make some changes to your ratings paths. At the moment, you're not getting ratings from issues generated by the `scss-lint` or `nodesecurity` engines, since `*.scss` files and `npm-shrinkwrap.json` files aren't included within the following ratings paths:

``` yaml
ratings:
  paths:
  - "**.css"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
```

Looks the following config would work better for you; adding `.scss` and `npm-shrinkwrap.json`. Additionally for some cleanup you could remove the php-specific paths (`**.inc`, and `**.module`) and remove the `**.jsx` rating path (I don't see any JSX templates here):

``` yaml
ratings:
  paths:
  - "**.css"
  - "**.scss"
  - "**.js"
  - "npm-shrinkwrap.json"
```

**Comment by dblandin** [comment]
Another quick note: Looks like our duplication engine is [emitting issues](https://codeclimate.com/github/sfbrigade/brigadehub/issues?engine=duplication) for some of your vendored assets. You probably want to exclude those paths from analysis:

``` yaml
exclude_paths:
- themes/codeforpoland/public/css/vendors
- themes/codeforpoland/public/js/lib
```

**Pull request merged**
